TemplateExam/TemplateApp/urls.py
from django.urls import path
from . views import home, member, members

app_name = 'app'
urlpatterns = [
    path('home/',home, name='home'),
    path('members/',members, name= 'members'),
    path('member/<int:id>', member, name= 'member'),
    ]

TemplateExam/TemplateExam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('template_app/', include('TemplateApp.urls')),

]

TemplateExam/TemplateApp/models.py
from django.db import models

# Create your models here.

TemplateExam/TemplateApp/views.py
from django.shortcuts import render


class Member:
    
    def __init__(self, id, name, join_at, picture_path):
        self.id = id
        self.name = name
        self.join_at = join_at
        self.picture_path = picture_path

member_list = [
    Member(0, 'Taro','2018/04/01', 'img/taro.jpg'),
    Member(1, 'Jiro','2019/04/01','img/jiro.jpg'),
    Member(2, 'Hanako','2019/05/01','img/hanako.jpg'),
    Member(3, 'Yoshiko','2018/10/01','img/yoshiko.jpg'),
]


#ホーム画面
def home(request):
    return render(request, 'home.html')

#メンバー一覧
def members(request):
    return render(request,'members.html', context={
        'members': member_list
    })
#メンバーの画面詳細
def member(request,id):
    return render(request, 'member_detail.html', context={
        'member': member_list[id]
    })

TemplateExam/TemplateApp/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>{% block title %}Django大学陸上部{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <nav class= "navbar navbar-expand-lg navbar-light bg-light">
      <a class "navber-brand" href= "{% url 'app: home' %}">Home</a>
      <a class "navber-brand" href= "{% url 'app: members' %}">メンバー一覧</a>
  </nav>  
  {% block content %}{% endblock%}
  </body>
</html>

TemplateExam/TemplateApp/templates/home.html
{% extends "base.html "%}
{% block title %}ホーム {{ block.super }}{% endblock %}
{% block content %}
<p>Django大学陸上部ホーム</p>
{% endblock %}

TemplateExam/TemplateApp/templates/member_detail.html
{% extends "base.html "%}
{% block title %}メンバー詳細 {{ block.super }}{% endblock %}
{% block content %}
{% load static %}
  <h1>メンバー詳細画面</h1>
  <img src= "{% static member.picture_path %}">
  <p>名前: {{ member.name }}</p>
  <p>入部日: {{ member.join_at }}</p>
{% endblock %}

TemplateExam/TemplateApp/templates/members.html
{% extends "base.html "%}
{% block title %}メンバー一覧 {{block.super }}{% endblock %}
{% block content %}
{% for member in members %}
  <p><a href= "{% url 'app:member' id= member.id %}">{{ member.name }}</p>
{% endfor %}
{% endblock %}

TemplateExam/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>{% block title %}Django大学陸上部{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <nav class= "navbar navbar-expand-lg navbar-light bg-light">
      <a class "navber-brand" href= "{% url 'app: home' %}">Home</a>
      <a class "navber-brand" href= "{% url 'app: members' %}">メンバー一覧</a>
  </nav>  
  {% block content %}{% endblock%}
  </body>
</html>

TemplateExam/templates/home.html
{% extends "base.html "%}
{% block title %}ホーム {{ block.super }}{% endblock %}
{% block content %}
<p>Django大学陸上部ホーム</p>
{% endblock %}

TemplateExam/templates/member_detail.html
{% extends "base.html "%}
{% block title %}メンバー詳細 {{ block.super }}{% endblock %}
{% block content %}
{% load static %}
  <h1>メンバー詳細画面</h1>
  <img src= "{% static member.picture_path %}">
  <p>名前: {{ member.name }}</p>
  <p>入部日: {{ member.join_at }}</p>
{% endblock %}

TemplateExam/templates/members.html
{% extends "base.html "%}
{% block title %}メンバー一覧 {{block.super }}{% endblock %}
{% block content %}
{% for member in members %}
  <p><a href= "{% url 'app:member' id= member.id %}">{{ member.name }}</p>
{% endfor %}
{% endblock %}